/**
 * generated by Xtext
 */
package com.cburch.logisim.statemachine.validation;

import com.cburch.logisim.statemachine.validation.AbstractFSMDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class FSMDSLValidator extends AbstractFSMDSLValidator {
}
