/**
 * generated by Xtext
 */
package com.cburch.logisim.statemachine.fSMDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bool Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.cburch.logisim.statemachine.fSMDSL.FSMDSLPackage#getBoolExpr()
 * @model
 * @generated
 */
public interface BoolExpr extends EObject
{
} // BoolExpr
