/**
 * generated by Xtext
 */
package com.cburch.logisim.statemachine.fSMDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Default Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.cburch.logisim.statemachine.fSMDSL.FSMDSLPackage#getDefaultPredicate()
 * @model
 * @generated
 */
public interface DefaultPredicate extends BoolExpr
{
} // DefaultPredicate
