/**
 * generated by Xtext
 */
package com.cburch.logisim.statemachine.fSMDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Port</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.cburch.logisim.statemachine.fSMDSL.FSMDSLPackage#getInputPort()
 * @model
 * @generated
 */
public interface InputPort extends Port
{
} // InputPort
