/**
 * generated by Xtext
 */
package com.cburch.logisim.statemachine.fSMDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>TOP</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.cburch.logisim.statemachine.fSMDSL.FSMDSLPackage#getTOP()
 * @model
 * @generated
 */
public interface TOP extends EObject
{
} // TOP
