/*
 * generated by Xtext
 */
package com.cburch.logisim.statemachine;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FSMDSLRuntimeModule extends com.cburch.logisim.statemachine.AbstractFSMDSLRuntimeModule {

}
