/*
 * generated by Xtext
 */
package com.cburch.logisim.statemachine;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class FSMDSLStandaloneSetup extends FSMDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new FSMDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

