/*
 * Logisim-evolution - digital logic design tool and simulator
 * Copyright by the Logisim-evolution developers
 *
 * https://github.com/logisim-evolution/
 *
 * This is free software released under GNU GPLv3 license
 */

package com.cburch.logisim.vhdl.sim;

import com.cburch.logisim.generated.BuildInfo;
import com.cburch.logisim.util.FileUtil;
import com.cburch.logisim.util.LocaleManager;
import com.cburch.logisim.vhdl.base.VhdlParser;
import com.cburch.logisim.vhdl.base.VhdlSimConstants;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Generates a simulation top file. This file contains all the interfaces to the entities (in and
 * out pins) so the simulation is run on a single top component. It allows us to have only one
 * instance of Questasim running.
 *
 * @author christian.mueller@heig-vd.ch
 */
public class VhdlSimulatorVhdlTop {
  static final Logger logger = LoggerFactory.getLogger(VhdlSimulatorVhdlTop.class);
  private boolean valid = false;
  private boolean firstPort;
  private boolean firstComp;
  private boolean firstMap;

  public void fireInvalidated() {
    valid = false;
  }

  /**
   * If the top file has been invalidated, regenerates the VHDL top file.
   */
  public void generate(List<VhdlSimulatorComponent> comps) {
    /* Do not generate if file is already valid */
    if (valid) {
      return;
    }

    final var template = buildTop(comps);
    if (template == null) return;

    try (final var writer =
        new PrintWriter(
            VhdlSimConstants.SIM_SRC_PATH + VhdlSimConstants.SIM_TOP_FILENAME,
            StandardCharsets.UTF_8)) {
      writer.print(template);
    } catch (IOException e) {
      logger.error("Could not create top_sim file : {}", e.getMessage());
      return;
    }

    valid = true;
  }

  String buildTop(List<VhdlSimulatorComponent> comps) {

    final var lineSeparator = System.getProperty("line.separator");

    final var ports = new StringBuilder();
    ports.append(String.format("Autogenerated by %s --", BuildInfo.displayName));
    ports.append(lineSeparator);

    final var components = new StringBuilder();
    components.append(String.format("Autogenerated by %s --", BuildInfo.displayName));
    components.append(lineSeparator);

    final var map = new StringBuilder();
    map.append(String.format("Autogenerated by %s --", BuildInfo.displayName));
    map.append(lineSeparator);

    firstPort = firstComp = firstMap = true;
    final var declaredEntities = new HashSet<String>();

    /* For each vhdl entity */
    for (final var comp : comps) {
      final var vhdlEntityName = comp.entityName();
      final var simulationName = comp.simulationName();
      final var myPorts = comp.ports();

      /*
       * Create ports
       */
      for (final var port : myPorts) {
        if (!firstPort) {
          ports.append(";");
          ports.append(lineSeparator);
        } else {
          firstPort = false;
        }
        final var portName = simulationName + "_" + port.getName();
        ports
            .append("      ")
            .append(portName)
            .append(" : ")
            .append(port.getVhdlType())
            .append(" std_logic");
        int width = port.getWidth().getWidth();
        if (width > 1) {
          ports.append("_vector(").append(width - 1).append(" downto 0)");
        }
      }

      /*
       * Create components
       */
      if (declaredEntities.add(vhdlEntityName.toLowerCase(Locale.ROOT))) {
        components.append("   component ").append(vhdlEntityName);
        components.append(lineSeparator);

        components.append("      port (");
        components.append(lineSeparator);

        firstComp = true;
        for (final var port : myPorts) {
          if (!firstComp) {
            components.append(";");
            components.append(lineSeparator);
          } else {
            firstComp = false;
          }

          components
              .append("         ")
              .append(port.getName())
              .append(" : ")
              .append(port.getVhdlType())
              .append(" std_logic");

          int width = port.getWidth().getWidth();
          if (width > 1) {
            components.append("_vector(").append(width - 1).append(" downto 0)");
          }
        }

        components.append(lineSeparator);
        components.append("      );");
        components.append(lineSeparator);

        components.append("   end component ;");
        components.append(lineSeparator);

        components.append("   ");
        components.append(lineSeparator);
      }

      /*
       * Create port map
       */
      map.append("   ")
          .append(simulationName)
          .append("_map : ")
          .append(vhdlEntityName)
          .append(" port map (");
      map.append(lineSeparator);

      firstMap = true;
      for (final var port : myPorts) {

        if (!firstMap) {
          map.append(",");
          map.append(lineSeparator);
        } else {
          firstMap = false;
        }

        map.append("      ")
            .append(port.getName())
            .append(" => ")
            .append(simulationName)
            .append("_")
            .append(port.getName());
      }
      map.append(lineSeparator);
      map.append("   );");
      map.append(lineSeparator);
      map.append("   ");
      map.append(lineSeparator);
    }

    ports.append(lineSeparator);
    ports.append("      ---------------------------");
    ports.append(lineSeparator);

    components.append("   ---------------------------");
    components.append(lineSeparator);

    map.append("   ---------------------------");
    map.append(lineSeparator);

    /*
     * Replace template blocks by generated datas
     */
    String template;
    try {
      template =
          new String(
              FileUtil.getBytes(
                  this.getClass()
                      .getResourceAsStream(
                          VhdlSimConstants.VHDL_TEMPLATES_PATH + "top_sim.templ")));
    } catch (IOException e) {
      logger.error("Could not read template : {}", e.getMessage());
      return null;
    }

    return template
        .replace("%date%", LocaleManager.PARSER_SDF.format(new Date()))
        .replace("%ports%", ports.toString())
        .replace("%components%", components.toString())
        .replace("%map%", map.toString());
  }
}
