/*
 * generated by Xtext
 */
package com.cburch.logisim.statemachine.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFSMDSLScopeProvider extends DelegatingScopeProvider {
}
