/*
 * Logisim-evolution - digital logic design tool and simulator
 * Copyright by the Logisim-evolution developers
 *
 * https://github.com/logisim-evolution/
 *
 * This is free software released under GNU GPLv3 license
 */

package com.cburch.logisim.std.wiring;

import com.cburch.logisim.circuit.RadixOption;
import com.cburch.logisim.data.Attribute;
import com.cburch.logisim.data.AttributeOption;
import com.cburch.logisim.data.Attributes;
import com.cburch.logisim.data.BitWidth;
import com.cburch.logisim.data.Value;
import com.cburch.logisim.instance.StdAttr;

import java.util.Arrays;
import java.util.List;

import static com.cburch.logisim.circuit.Strings.S;

class PinAttributes extends ProbeAttributes {
  /* I introduced the dummy attribute to be backward compatible with files generated by
   * the holycross branch of logisim (v4.0 up). Now used to fix toolbar Pins from < v4.0.
   * FIXME: This should be done in XML input for the toolbar.
   */
  public static final Attribute<Boolean> ATTR_DUMMY = Attributes.forBoolean("output", S.getter("dummy")); //new DummyAttr("type");
  public static PinAttributes instance = new PinAttributes();
  private static final List<Attribute<?>> INPIN_ATTRIBUTES = Arrays
      .asList(StdAttr.FACING, Pin.ATTR_TYPE,
          StdAttr.WIDTH, Pin.ATTR_BEHAVIOR,
          StdAttr.LABEL, StdAttr.LABEL_LOC, StdAttr.LABEL_FONT,
          RadixOption.ATTRIBUTE, PROBEAPPEARANCE, Pin.ATTR_INITIAL, ATTR_DUMMY);
  private static final List<Attribute<?>> TRISTATE_ATTRIBUTES = Arrays
      .asList(StdAttr.FACING, Pin.ATTR_TYPE,
          StdAttr.WIDTH, Pin.ATTR_BEHAVIOR,
          StdAttr.LABEL, StdAttr.LABEL_LOC, StdAttr.LABEL_FONT,
          RadixOption.ATTRIBUTE, PROBEAPPEARANCE /*, Pin.ATTR_INITIAL */, ATTR_DUMMY);
  private static final List<Attribute<?>> OUTPIN_ATTRIBUTES = Arrays
      .asList(StdAttr.FACING, Pin.ATTR_TYPE,
          StdAttr.WIDTH, /*Pin.ATTR_BEHAVIOR, */
          StdAttr.LABEL, StdAttr.LABEL_LOC, StdAttr.LABEL_FONT,
          RadixOption.ATTRIBUTE, PROBEAPPEARANCE /*, Pin.ATTR_INITIAL */, ATTR_DUMMY);

  BitWidth width = BitWidth.ONE;
  AttributeOption type = Pin.INPUT;
  AttributeOption behavior = Pin.SIMPLE;
  Long initialValue = 0L;

  public PinAttributes() {
    ATTR_DUMMY.setHidden(true);
  }

  @Override
  public List<Attribute<?>> getAttributes() {
    return type == Pin.INPUT
        ? (behavior == Pin.TRISTATE ? TRISTATE_ATTRIBUTES : INPIN_ATTRIBUTES)
        : OUTPIN_ATTRIBUTES;
  }

  @Override
  public boolean isToSave(Attribute<?> attr) {
    return attr.isToSave() && attr != ATTR_DUMMY;
  }

  @Override
  @SuppressWarnings("unchecked")
  public <V> V getValue(Attribute<V> attr) {
    if (attr == StdAttr.WIDTH) return (V) width;
    if (attr == Pin.ATTR_TYPE) return (V) type;
    if (attr == Pin.ATTR_BEHAVIOR) return (V) behavior;
    if (attr == PROBEAPPEARANCE) return (V) appearance;
    if (attr == ATTR_DUMMY) return (V) Boolean.valueOf(type == Pin.OUTPUT);
    if (attr == Pin.ATTR_INITIAL) return (V) initialValue;
    return super.getValue(attr);
  }

  boolean isInput() {
    return type == Pin.INPUT;
  }

  boolean isOutput() {
    return type == Pin.OUTPUT;
  }

  Value defaultBitValue() {
    return isOutput() ? Value.UNKNOWN : behavior == Pin.PULL_UP ? Value.TRUE : Value.FALSE;
  }

  boolean isClock() {
    if (isOutput()) return false;

    String lbl = getValue(StdAttr.LABEL);
    if (lbl == null) return false;

    return lbl.matches("(?i).*(clk|clock).*");
  }

  @SuppressWarnings("unchecked")
  @Override
  public <V> void setValue(Attribute<V> attr, V value) {
    if (attr == ATTR_DUMMY) {
      if ((boolean) value) {
        if (type != Pin.OUTPUT) {
          type = Pin.OUTPUT;
          fireAttributeValueChanged(
              (Attribute<V>) Pin.ATTR_TYPE, value, null);
          return;
        }
      }
    } else if (attr == StdAttr.WIDTH) {
      BitWidth NewWidth = (BitWidth) value;
      if (width == NewWidth) return;
      width = (BitWidth) value;
      if (width.getWidth() > 8 && appearance == ProbeAttributes.APPEAR_EVOLUTION_NEW)
        super.setValue(RadixOption.ATTRIBUTE, RadixOption.RADIX_16);
    } else if (attr == Pin.ATTR_TYPE) {
      if (type.equals(value)) return;
      type = (AttributeOption) value;
      fireAttributeListChanged();
    } else if (attr == Pin.ATTR_BEHAVIOR) {
      if (behavior.equals(value)) return;
      behavior = (AttributeOption) value;
    } else if (attr == PROBEAPPEARANCE) {
      final var newAppearance = (AttributeOption) value;
      if (appearance.equals(newAppearance)) return;
      appearance = newAppearance;
    } else if (attr == RadixOption.ATTRIBUTE) {
      if (width.getWidth() == 1) {
        super.setValue(RadixOption.ATTRIBUTE, RadixOption.RADIX_2);
      } else super.setValue(attr, value);
      return;
    } else if (attr == Pin.ATTR_INITIAL) {
      final var newInitial = (Long) value;
      if (newInitial == initialValue) return;
      initialValue = newInitial;
    } else {
      super.setValue(attr, value);
      return;
    }
    fireAttributeValueChanged(attr, value, null);
  }
}
