/**
 * generated by Xtext
 */
package com.cburch.logisim.statemachine.formatting2;

import com.cburch.logisim.statemachine.services.FSMDSLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class FSMDSLFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private FSMDSLGrammarAccess _fSMDSLGrammarAccess;
  
  @Override
  public void format(final Object obj, final IFormattableDocument document) {
    throw new UnsupportedOperationException("TODO: auto-generated method stub");
  }
}
